# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39ce27e1d41517b6385164e03e0645d52815f751a5ead58e74e5a0729df0b0984bb0cf53444f5b90f1d4ae551ba4d6835a6897d7594b498be487b2190b1bd15c

test:
  secret_key_base: c65d7602c8f96e82e5f8cf77059ad783df7c56e8884d2d0da4a8f6ed4bee37365af21875b009870d8639b1d303c596d92b2dcab89cf7ae41ce227fe359f4a6c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
